<?php

namespace Esprit\AbsenceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbsenceListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceListRepository extends EntityRepository
{
}
