<?php

namespace Esprit\EnseignantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbsenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbsenceRepository extends EntityRepository
{
    public function listAbsence($classe, $matiere, $prof, $date, $creneau){
        $stmt = $this->getEntityManager()
                ->getConnection()
                ->prepare('SELECT
            *
        FROM
            esp_absence 
        WHERE
            classe_id=:? AND MATIERE_ID=:? AND ENSEIGNANT_ID=:2
            AND DATE_SAISIE=:? AND HEUREABSENCE=:?

                      ');
        $stmt->bindValue('1', $classe);
        $stmt->bindValue('2', $matiere);
        $stmt->bindValue('3', $prof);
        $stmt->bindValue('4', $date);
        $stmt->bindValue('5', $creneau);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
