<?php

namespace Esprit\EnseignantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends EntityRepository
{
    public function listClasse($idprof)
    {
        $stmt = $this->getEntityManager()
                ->getConnection()
                ->prepare('        SELECT
            *
        FROM
            esp_classe 
        WHERE
           id IN
            (SELECT classe_id 
            FROM affectation  
            WHERE 
            enseignant_id=:ens )

                      ');
        $stmt->bindValue('ens', $idprof);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
