<?php

namespace Esprit\EnseignantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspRdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspRdiRepository extends EntityRepository
{
}
