<?php

namespace Esprit\EnseignantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspTacheRdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspTacheRdiRepository extends EntityRepository
{
}
