<?php

namespace Esprit\EnseignantBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends EntityRepository {

    public function listMatiere($idclass) {
        $stmt = $this->getEntityManager()
                ->getConnection()
                ->prepare('        SELECT
            *
        FROM
            esp_matiere 
        WHERE
           id IN
            (SELECT matiere_id 
            FROM matiere_classe  
            WHERE 
            classe_id=:classe )

                      ');
        $stmt->bindValue('classe', $idclass);
        $stmt->execute();
        return $stmt->fetchAll();
    }
    

}
