<?php

namespace Proxies\__CG__\Esprit\UserBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ProjetRdi extends \Esprit\UserBundle\Entity\ProjetRdi implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUR($uR)
    {
        $this->__load();
        return parent::setUR($uR);
    }

    public function getUR()
    {
        $this->__load();
        return parent::getUR();
    }

    public function setDateaffectation($dateaffectation)
    {
        $this->__load();
        return parent::setDateaffectation($dateaffectation);
    }

    public function getDateaffectation()
    {
        $this->__load();
        return parent::getDateaffectation();
    }

    public function setTitre($titre)
    {
        $this->__load();
        return parent::setTitre($titre);
    }

    public function getTitre()
    {
        $this->__load();
        return parent::getTitre();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setEspens(\Esprit\UserBundle\Entity\EspEnseignant $espens = NULL)
    {
        $this->__load();
        return parent::setEspens($espens);
    }

    public function getEspens()
    {
        $this->__load();
        return parent::getEspens();
    }

    public function addTache(\Esprit\UserBundle\Entity\TacheRdi $taches)
    {
        $this->__load();
        return parent::addTache($taches);
    }

    public function removeTache(\Esprit\UserBundle\Entity\TacheRdi $taches)
    {
        $this->__load();
        return parent::removeTache($taches);
    }

    public function getTaches()
    {
        $this->__load();
        return parent::getTaches();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'uR', 'dateaffectation', 'titre', 'description', 'espens', 'taches');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}