<?php

namespace Proxies\__CG__\Esprit\EnseignantBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Module extends \Esprit\EnseignantBundle\Entity\Module implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function setNbHeure($nbHeure)
    {
        $this->__load();
        return parent::setNbHeure($nbHeure);
    }

    public function getNbHeure()
    {
        $this->__load();
        return parent::getNbHeure();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addAbsencelist(\Esprit\EnseignantBundle\Entity\AbsenceList $absencelist)
    {
        $this->__load();
        return parent::addAbsencelist($absencelist);
    }

    public function removeAbsencelist(\Esprit\EnseignantBundle\Entity\AbsenceList $absencelist)
    {
        $this->__load();
        return parent::removeAbsencelist($absencelist);
    }

    public function getAbsencelist()
    {
        $this->__load();
        return parent::getAbsencelist();
    }

    public function addMatiere(\Esprit\EnseignantBundle\Entity\Matiere $matieres)
    {
        $this->__load();
        return parent::addMatiere($matieres);
    }

    public function removeMatiere(\Esprit\EnseignantBundle\Entity\Matiere $matieres)
    {
        $this->__load();
        return parent::removeMatiere($matieres);
    }

    public function getMatieres()
    {
        $this->__load();
        return parent::getMatieres();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'libelle', 'nbHeure', 'absencelist', 'matieres');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}