<?php

namespace Proxies\__CG__\Esprit\EnseignantBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Classe extends \Esprit\EnseignantBundle\Entity\Classe implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function addAbsencelist(\Esprit\EnseignantBundle\Entity\AbsenceList $absencelist)
    {
        $this->__load();
        return parent::addAbsencelist($absencelist);
    }

    public function removeAbsencelist(\Esprit\EnseignantBundle\Entity\AbsenceList $absencelist)
    {
        $this->__load();
        return parent::removeAbsencelist($absencelist);
    }

    public function getAbsencelist()
    {
        $this->__load();
        return parent::getAbsencelist();
    }

    public function addEnseignant(\Esprit\UserBundle\Entity\EspEnseignant $enseignants)
    {
        $this->__load();
        return parent::addEnseignant($enseignants);
    }

    public function removeEnseignant(\Esprit\UserBundle\Entity\EspEnseignant $enseignants)
    {
        $this->__load();
        return parent::removeEnseignant($enseignants);
    }

    public function getEnseignants()
    {
        $this->__load();
        return parent::getEnseignants();
    }

    public function addAbsence(\Esprit\EnseignantBundle\Entity\Absence $absences)
    {
        $this->__load();
        return parent::addAbsence($absences);
    }

    public function removeAbsence(\Esprit\EnseignantBundle\Entity\Absence $absences)
    {
        $this->__load();
        return parent::removeAbsence($absences);
    }

    public function getAbsences()
    {
        $this->__load();
        return parent::getAbsences();
    }

    public function addEtudiant(\Esprit\UserBundle\Entity\EspEtudiant $etudiants)
    {
        $this->__load();
        return parent::addEtudiant($etudiants);
    }

    public function removeEtudiant(\Esprit\UserBundle\Entity\EspEtudiant $etudiants)
    {
        $this->__load();
        return parent::removeEtudiant($etudiants);
    }

    public function getEtudiants()
    {
        $this->__load();
        return parent::getEtudiants();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'libelle', 'absencelist', 'enseignants', 'absences', 'etudiants');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}