<?php

namespace Esprit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspCongesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspCongesRepository extends EntityRepository
{
}
