<?php

namespace Esprit\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EspCursusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspCursusRepository extends EntityRepository
{
}
