<?php

namespace Esprit\EnseignantBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AbsenceController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\EnseignantBundle\Controller\AbsenceController();
        return $instance;
    }
}
