<?php

namespace Esprit\EnseignantBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClasseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\EnseignantBundle\Controller\ClasseController();
        return $instance;
    }
}
