<?php

namespace Proxies\__CG__\Esprit\UserBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EspNote extends \Esprit\UserBundle\Entity\EspNote implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTp($tp)
    {
        $this->__load();
        return parent::setTp($tp);
    }

    public function getTp()
    {
        $this->__load();
        return parent::getTp();
    }

    public function setCc($cc)
    {
        $this->__load();
        return parent::setCc($cc);
    }

    public function getCc()
    {
        $this->__load();
        return parent::getCc();
    }

    public function setEx($ex)
    {
        $this->__load();
        return parent::setEx($ex);
    }

    public function getEx()
    {
        $this->__load();
        return parent::getEx();
    }

    public function setMatiere($matiere)
    {
        $this->__load();
        return parent::setMatiere($matiere);
    }

    public function getMatiere()
    {
        $this->__load();
        return parent::getMatiere();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tp', 'cc', 'ex', 'matiere');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}