espetudiant:
    pattern:  /
    defaults: { _controller: "EspritUserBundle:EspEtudiant:index" }
espetudiant:
    pattern:  /ficheetudiant
    defaults: { _controller: "EspritUserBundle:EspEtudiant:fiche" }
esp_ficheeleve:
    pattern:  /ficheeleve
    defaults: { _controller: "EspritUserBundle:EspEtudiant:ficheeleve" }
espetudiant_listetudiant:
    pattern:  /listetudiant
    defaults: { _controller: "EspritUserBundle:EspEtudiant:listetudiant" }
espetudiant_show:
    pattern:  /{id}/show
    defaults: { _controller: "EspritUserBundle:EspEtudiant:show" }
espetudiant_listebyclasse:
    pattern:  /{id}/listebyclasse
    defaults: { _controller: "EspritUserBundle:EspEtudiant:listByClasse" }
espetudiant_new:
    pattern:  /new
    defaults: { _controller: "EspritUserBundle:EspEtudiant:new" }
espetudiant_enc:
    pattern:  /encadrement
    defaults: { _controller: "EspritUserBundle:EspEtudiant:encadrement" }

espetudiant_create:
    pattern:  /create
    defaults: { _controller: "EspritUserBundle:EspEtudiant:create" }
    requirements: { _method: post }

espetudiant_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EspritUserBundle:EspEtudiant:edit" }

espetudiant_update:
    pattern:  /{id}/update
    defaults: { _controller: "EspritUserBundle:EspEtudiant:update" }
    requirements: { _method: post|put }

espetudiant_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EspritUserBundle:EspEtudiant:delete" }
    requirements: { _method: post|delete }
